version: '3.9'

services:
  tilemap-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tilemap-app
    depends_on:
      - redis
    environment:
      - REDIS_CONNECTION=redis:6379
    ports:
      - "5000:5000"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
